#ifndef __JRASTRO_H_
#define __JRASTRO_H_

#define JRST_INITIALIZE 0
#define JRST_FINALIZE 1
#define JRST_MONITOR_ENTER 2
#define JRST_MONITOR_ENTERED 3
#define JRST_MONITOR_WAIT 4
#define JRST_MONITOR_WAITED 5
#define JRST_METHOD_ENTRY 6
#define JRST_METHOD_EXIT 7
#define JRST_METHOD_EXCEPTION 8
#define JRST_METHOD_EXIT_EXCEPTION 9
#define JRST_METHOD_LOAD 10
#define JRST_CLASS_LOAD 11


#endif
